### ISSUE TITLE
Плагин перестал скачивать картинки

### ISSUE THREAD

**Issue by Nathman999** [NC22/KellyCFavorites#2]
Вместо скачивания в консоль приходят вот такие ошибки:
1. `Access to XMLHttpRequest at 'http://img0.joyreactor.cc/pics/post/full/%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0-%D0%BF%D0%B8%D0%B4%D0%BE%D1%80%D1%8B-%D0%BF%D0%BE%D0%BC%D0%BE%D0%B3%D0%B8%D1%82%D0%B5-5167914.png' from origin 'http://joyreactor.cc' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

2. `GET http://img0.joyreactor.cc/pics/post/full/%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0-%D0%BF%D0%B8%D0%B4%D0%BE%D1%80%D1%8B-%D0%BF%D0%BE%D0%BC%D0%BE%D0%B3%D0%B8%D1%82%D0%B5-5167914.png net::ERR_FAILED`

**Comment by NC22** [comment]
Были ли изменения в окружении (смена провайдера \ установка доп. плагинов вроде анонимайзеров \ vpn \ блокировщиков реклами и т.п.) ?

Сохраняются ли ошибки при смене метода загрузки (XMLHttpRequest \ Fetch \ Iframe hook)? подробнее по смене настроек здесь https://github.com/NC22/KellyCFavorites/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%B8-%D0%B7%D0%B0%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D1%8F

**Comment by Nathman999** [comment]
Гугл хром 85.0.4183.83
1.Провайдер не менялся.
2.Проверил с отключением всех плагинов кроме этого, не помогло.
3. Начало скачивать с  Iframe hook и отключением адблока (uBlock Origin).

Грубо говоря проблема решена, хотя и не понятно с чего вдруг перестал старый способ работать.
Спасибо

**Comment by NC22** [comment]
Ясно. Так то в общей ситуации должен работать и прямой запрос. Тоже с последней версии хрома сижу, такой проблемы никогда не возникало. Еще вроде как расширениям пользователь может отрубать определенные разрешения \ доступ к отдельным ресурсам, возможно хром по какой то причине обрубил доступ расширению что привело к проблемам к межсайтовым запросам, но я не углублялся в то как это можно воспроизвести. Быть может если переустановить расширение проблема пропадет.

**Comment by NC22** [comment]
> Быть может если переустановить расширение проблема пропадет. (только данные \ списки засейвить не забудь если будешь тестить)

Можно без переустановки еще просто проверить параметр "Доступ к сайтам" в параметрах расширения - должно быть "На всех сайтах". [Расширения - KellyC Favorites - Подробнее - Доступ к сайтам - На всех сайтах]

**Comment by Nathman999** [comment]
Начал копать в эту проблему. Нашёл специальный плагин для хрома (и походу для многих других браузеров похожие есть) который как-то отключает этот CORS и даёт доступ подобным запросам. Ещё в chrome://flags/ нашёл такой флаг CORS for content scripts вроде как после того как поставил его на Disabled сразу заработало всё. Наверное у тебя именно это и стоит там, поэтому и проблем таких не было.

**Comment by Nathman999** [comment]
И самое смешное что на https://webbrowsertools.com/test-cors/ всё ещё блочит запросы, хотя в плагине на джое они заработали

**Comment by NC22** [comment]
> Начал копать в эту проблему. Нашёл специальный плагин для хрома (и походу для многих других браузеров похожие есть)

да, плагины существуют, тоже как вариант. Можно активировать, но лучше включать только при необходимости чтобы на рандомных сайтах не давать такой возможности.

> Ещё в chrome://flags/ нашёл такой флаг CORS for content scripts вроде как после того как поставил его на Disabled сразу заработало всё

Спасибо за инфу. Думаю этот флаг разлочивает cors на все расширения без разбора что тоже не совсем безопасно, но если особо расширений нет то это хороший вариант.  Мое расширение при установке как раз таки по идее уже  получает разрешение на чтение всех сайтов через параметр [permissions - all_urls] и без него как раз таки изначально при разработке сталкивался со всеми описанными тобой проблемами т.к. реактор держит данные на разных поддоменах \ доменах. По какой причине оно перестало срабатывать в твоем случае не понятно. Единственное предположение было что разрешения могли сбиться или появились какие-то доп. ограничения которые мне пока не понятны.

**Comment by NC22** [comment]
На днях тоже столкнулся с этой проблемой на новой версии хрома, так что была возможность протестировать и пофиксить. В версии 1.1.5.2 расширения добавил доп. привелегии для обхода ограничений CORS в само расширение. Так что сейчас впринципе поумолчанию любой способ скачивания (Fetch \ XmlHttpRequest) должен работать без перенастройки флагов \ установки спец. расширений и т.д.
